version: "3.8"

services:
  app:
    image: shinsenter/symfony:dev-latest
    container_name: symfony_app
    restart: unless-stopped
    ports:
      - "80:80"  # Expose directement le port 80
    volumes:
      - .:/var/www/html
      - ./var/cache:/var/www/html/var/cache
      - ./var/log:/var/www/html/var/log
    environment:
      APP_ENV: prod
      APP_SECRET: mysupersecretkey
      DATABASE_URL: mysql://app_user:app_password@mysql:3306/app_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - symfony_network

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    networks:
      - symfony_network

volumes:
  mysql-data:
    driver: local

networks:
  symfony_network:
    driver: bridge
